language: node_js
sudo: false
node_js:
- '7'
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run build
- mkdir upload
- mkdir upload/static
- mkdir upload/static/js
- mkdir upload/static/css
- cp build/index.html upload/index.html
- cp build/static/js/main.js.gz upload/static/js/main.js.gz
- cp build/static/css/main.css.gz upload/static/css/main.css.gz
- echo "{'availableVersion':'$TRAVIS_BUILD_NUMBER'}" > upload/webclient.json
deploy:
  skip_cleanup: true
  provider: s3
  bucket: antroids-webstrip
  upload-dir: webclient
  local-dir: upload
  access_key_id:
    secure: vZJ9Q6fw+ZjHaS78Nuj2YOCEneOuYvqaUT/ZrHgYqfIzPKvKhcExUW0IKajNTFOPkuv92lHZ3wX9s2vkt0opGXqPP4kmJKTRpfoyXXdxlPb+PNzLIQzi7mPiQQKTL03Pkbb6S8NkAoaMUFTErVvfQUFxXS0judxjWPBTtlZxqgh+qw6PzCYtrst2BDHooulx4YcXm9G430pICmTc0xJFqJrUMCcWzmXEOnVN7HRvyOiLL/N7VgGqlk9oh1A4Nq5M8L9sJ+Ldg1HosG5e1aP0glrr8Ss04ex4DqR6DfxNQK95jk/yvf9N2UcXn5HsI+9bv1BD8w3vpLCMrbh90e0aubYQqvZU7B6UCZSYhGVJBaBKlDQtFDPtF6zRrFJNQNJFoCQdteH52puhncDsn/NrbJCEBNQNPGBGZX7JSdD7ZLjaoQi9Y6rRylWHBwMhmMS0c9heMWEN9F79A5+5aATd7kTvfv4l11NoFRrfJFyJijm6iLEqDK2thnnelnPglCS6GKVNUguDPEZFScVPYlutIPJry1/a5gd/Q7nk5OxhPu7DiWjPL3o1reN4Uc3Xhneq4/7obxbK0bRwYCwpFf5ptC65FZLt4taPI0xEsQIJD55/VtyoJ9mUD39x6xABQcFxYpDMPnsFZ+mLG5RcazW8m0llq4RqDIOiUN+vu4OFH+I=
  secret_access_key:
    secure: imcJMR9fGmpjAbNIK1kTeT1fVK0a4KsX97NYlWgZfSAnD8wGvgspfDzW6e+XOd+xorgd9WklDAAZZ9ypSdYBNjkagHfPwgYtyo8X+F4SjzSY9PX3hTzipYadPQq+9ISb39c1dzMr+XAv2c/ZwxPPOWgMZIIUp4rk+uQZVltAIOpXUX03v3Y7RCuWTKPcXC4rG+ENarMoOvd+4hF8h/vOjleSoSYBwmpZc+BrywOQT0t+dwjOkDMRvh3ub94xFPbqVd+1wX+fisFAP5zt/u0v+1XZImKgDpjmCYZ1RCQk1pfxB6PHwknvqmsgo3wkqEI5Zn5PZINGQ0XD4WJNitcIdKe/DTF/UXfHuFZbN+bBLwDIG55Z285Aw90ArYoW5uMYzyOuw+h88kK1+yWc53gSYEkX3moLEG22j0gbSUbkXTz5GE9DL/mwWyvtRhwofe6qKZ6H+kLwYNt2vttOZ08WIGgpgc9DjHJm4pck/93bnNpe332+GT+AHaByGrKd5V0lQGXmEGkgRe62WI9cGSSIS6f7gz0gzRqj2HRFZSq71QP+n9w4OecCK29J7c7N0g0pnPfqW1fOujIFco56YdzVIPDkl5VmCG/G44q7g3SqrvG50T2mOcHKM7Tq3OEXYDgOk7vJqah9z0Zj649tPhS1IvqNOJ0GbXEIDhrhiLMvjfY=
