language: node_js
sudo: false
node_js:
- '7'
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run build
- mkdir upload
- mkdir upload/static
- mkdir upload/static/js
- mkdir upload/static/css
- cp build/index.html upload/index.html
- cp build/static/js/main.js.gz upload/static/js/main.js.gz
- cp build/static/css/main.css.gz upload/static/css/main.css.gz
deploy:
  file_glob: true
  skip_cleanup: true
  provider: s3
  access_key_id:
    - secure: ustPm8CAxZDuuPtAD70vtSl5eChUwhi8M5cXfkiD8LTxF1m2Lq/EmJj5VkbnO9bHX/O+B5mY+Yd+OLwJpDj1rjhAG4+f6bseV5CCe0Ay8bIpOCLPmOiu1p/8usAkXmVdbFaelNLf+Ybt4ywhq7D9HKwDXh1jHVF/uEiRMQ2dqRxvDHGrLPIqxZj3AcBTNBl9joRBzNoa0ugBoAWDqW2Wwcqp4zeBReinqrLAJFKTS03oG50be0JAcbDB6Mtr7wt5s9Rm1JNfI4aPCDpSLCtKRCtsoRe4AZ2gfiNoZR4T/FBfJwHHUaM2vQVWNLUY7Y/p7PrjvxO4fAIaMUOvRiXmhjEZ8jjnz7sWFmbmYL1kFzWaWFtuGAmP8cUqBC28sKZbbRcwZXKzMFSmk8U+Aij46Q3M0zZMQI7vc4kSB3VzfIZ9KEJYrLEY18tRmlRS3/Jr28uSRs9VSXJMudFqkJS7vBUknvojB1nXS80t0dmW3Gjuq50fOa/vkAA/6lNIIPY6nJNlFRxk3VahJcXcjWMI6JTI8qRLF3tgDIJX3sYMdw5ZN1LdyO4csJSNJm1e9BqumYInEmO1tWRMSAOT1usws6xaa2uDz5kj3MvlEdT5NxEJMJY3MI7S35rslvoCokygcx/l4DWQqeZsxrwSJVtsLLn+T6sF1tYhpuADHTSvIhI=
  secret_access_key:
    - secure: cWJdIn2DSKK8R4/NbIY6AoGOpL04V2kKI1U0zg408iWHXQhBaQD9ZUpSDTTupvxg3CQu2MAEJKSVXuOUIT4B4c3Jyw9UMQ0eBdtewsUlxtOaC1+UNv4fPk/zhBiIJCCpuN/kKEwBe52p1CKBFy9S9uzv9eWbSyRHUTmuBA+NXSVLf/Hlpr/tIpDqyIEJmAX9aubg071dBH0++GoAcNCEtKwFIy13je1khR+KDFsk2/PcPz6LhXPSmP+G3cAKUjmJtO2roK/VQWroo2rW1bys5FVT3gZC4st1MZcG+ljyEKcyJigUf9isuZaJDcBorRNwaQ+XF4osdaXlcb/50yFsh6nvWWdBJ9H1YJkZWnWKKO++uLxyiafrtaUKPhFxrwm21BoIHne5NdL2ehRx4j8xs2aTvd994Je/mRYsny5+avJcouNNiZuKr/j586EKeAuJRv1ITX+PseHgWglCTGBTCTtDv64rftzcBTxIlc47Ai2/pDF/HroI9bL38eY4w4d3CnSihZq68noWX26VtK0N8nyAnMPGBvXYF/X/RAQpEzbQNVJgC/jV1AGoxPbdK99LFg/E6NCEvUwMSXd108zyHlhR6qLlPHgW8P6kLCE0VkomHcV0jNaAwq4kliSUBJcr+dyAhQ9nNM3+Kih5q1m+RKBUWLeKPTw1LncIsFzrb/4=
  bucket: antroids-webstrip
  upload-dir: upload
