language: node_js
sudo: false
node_js:
- '7'
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run build
- mkdir upload
- mkdir upload/static
- mkdir upload/static/js
- mkdir upload/static/css
- cp build/index.html upload/index.html
- cp build/static/js/main.js.gz upload/static/js/main.js.gz
- cp build/static/css/main.css.gz upload/static/css/main.css.gz
deploy:
  skip_cleanup: true
  provider: s3
  bucket: antroids-webstrip
  upload-dir: upload
  access_key_id:
    secure: vZJ9Q6fw+ZjHaS78Nuj2YOCEneOuYvqaUT/ZrHgYqfIzPKvKhcExUW0IKajNTFOPkuv92lHZ3wX9s2vkt0opGXqPP4kmJKTRpfoyXXdxlPb+PNzLIQzi7mPiQQKTL03Pkbb6S8NkAoaMUFTErVvfQUFxXS0judxjWPBTtlZxqgh+qw6PzCYtrst2BDHooulx4YcXm9G430pICmTc0xJFqJrUMCcWzmXEOnVN7HRvyOiLL/N7VgGqlk9oh1A4Nq5M8L9sJ+Ldg1HosG5e1aP0glrr8Ss04ex4DqR6DfxNQK95jk/yvf9N2UcXn5HsI+9bv1BD8w3vpLCMrbh90e0aubYQqvZU7B6UCZSYhGVJBaBKlDQtFDPtF6zRrFJNQNJFoCQdteH52puhncDsn/NrbJCEBNQNPGBGZX7JSdD7ZLjaoQi9Y6rRylWHBwMhmMS0c9heMWEN9F79A5+5aATd7kTvfv4l11NoFRrfJFyJijm6iLEqDK2thnnelnPglCS6GKVNUguDPEZFScVPYlutIPJry1/a5gd/Q7nk5OxhPu7DiWjPL3o1reN4Uc3Xhneq4/7obxbK0bRwYCwpFf5ptC65FZLt4taPI0xEsQIJD55/VtyoJ9mUD39x6xABQcFxYpDMPnsFZ+mLG5RcazW8m0llq4RqDIOiUN+vu4OFH+I=
  secret_access_key:
    secure: qD/UPuy8lLpHhB7ZSu/IyPy2zqWmTu181Ej5rXhiaqpsiHEw7OOizbPZiOmJ2+CaHLrjSF9kYNd5V/nFxyl9IiSf0OsMCKv7crASpRxIA1z3aQFQPx4vyphsJ7mdhSyXkd0fJLujIWRl3JgqqbfP/rah8DLXwPCw4c5C6lS7Fywf4Nkmm5UzTdDU6F5Ab2X5dSLqhpBEWQP9ONwyigey99aot0z3iyzCJgJQm76VR0MBEbtq3YyCesaxhv6twDQDdyWZYb8ex9js+phVUXPM9uJ9qSVSNP9mLLTDorY9qUlmQvfIT4+gbTlo/dj4VLnNOfSlNLoRtOA323wuCCKmljEq83nrLw3eYGhMTsWyVkTxftXOrfkWx/jauM321Icif+tT1Y13Q4vEbkU2AZ5t+krUPT2BKcD1HE27mNKQnlWQRnJHfmUJKojslpM01QVJWDH55zbwSxBB24Pk972GgsdGDcCO1ANmskruvwXt8fsrakRH+J/EqxyCgBThPIRifp6t88zKY04Y7s9PXiuXvVosdRUo8EB4EBf6UalCCH3euM+QsDBcviVHWte1nY0K20mI9TUSIuB1dv8t3Xt0UUM7j6Zor63b4KDWD4T/pN909GdSJBY8g76qjHxcZnkTCES9ZMemasTH2qRjBZ/ZnhJtRQZx19X+ghfP5l7dYTU=
